version: '2'
services:
    flowabledemo-app:
        image: flowabledemo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://flowabledemo-mysql:3306/flowabledemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    flowabledemo-mysql:
        extends:
            file: mysql.yml
            service: flowabledemo-mysql
